project_id = "kfcinucmguijpvchehxe"

[functions.analyze-outfit]
verify_jwt = true

[functions.scrape-trends]
verify_jwt = false

[functions.analyze-tiktok-trends]
verify_jwt = true

[functions.scrape-common-hashtags]
verify_jwt = false
